


[build]
  command = "npm run build"
  publish = "dist/spa"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true
